version: '3.1'
services:
  magic-js:
    depends_on:
     - db
    build: '.'
    restart: unless-stopped
    ports:
     - "8081:8080"
    secrets:
     - db_password
    environment:
     - PGUSER=postgres
     - PGHOST=db
     - PGDATABASE=postgres
     - PGPASSFILE=/run/secrets/db_password
  db:
    build: ./postgres_initialize
    volumes:
      - /volume1/docker/magic/data:/var/lib/postgresql/data
    restart: unless-stopped
    secrets:
     - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  cron:
    build: ./cron
    restart: unless-stopped

secrets:
  db_password:
    file: db_password.txt